### PR TITLE
Resolve npm vulnerabilities

### PR DESCRIPTION
**Pull request by smalagon15**
Has resolution for frontend and backend dependencies. As well as some styling resolutions for material ui and bootstrap.

### CODE REVIEW

**Review by ryanryanchan — DISMISSED** [review]
looks good!

**Comment by smalagon15** [comment]
Should be good to go. The majority of the line changes are a result of running the script pretty in package.json Frontend. This formats the project to conform to eslint rules for tab spacing and using single quotes for strings.

**Review by ryanryanchan — APPROVED** [review]

**Review by ryanryanchan — DISMISSED** [review]

**Review by ryanryanchan — APPROVED** [review]

**Review by ryanryanchan — APPROVED** [review]

**Comment by smalagon15** [comment]
Handled todays merge conflicts and took out some unused variables

**Review by ryanryanchan — APPROVED** [review]

**Comment by smalagon15** [comment]
Handled some more merge conflicts should be good again

**Review by ryanryanchan — APPROVED** [review]

**Review by ryanryanchan — DISMISSED** [review]

**Review by JLyons1985 — APPROVED** [review]

**Review by ryanryanchan — APPROVED** [review]
at long last

**Pull request merged**
