### PR TITLE
UOT-100784 pass on user info

### PR DESCRIPTION
**Pull request by smalagon15**
defers putting in user info until page refresh

image

### CODE REVIEW

**Comment by DomCritchlow** [comment]
Is this every time you open a new page or click on any subpages? or just when you would be asked for your CAC again?

**Comment by smalagon15** [comment]
@DomCritchlow when the model is flagged to open for new users. If they exit out it will wait a day until it shows this again

**Comment by smalagon15** [comment]
image

I added a kill switch to deactivate the user feedback
Normally we have the values listed on the left I made it turn rose if it was  turned off

**Comment by smalagon15** [comment]
@JLyons1985 should we make all the toggle buttons turn colors?

**Comment by JLyons1985** [comment]
Yes I think thats a great idea, color for on and off and another if its just a button to start a process or something.

**Review by JLyons1985 — APPROVED** [review]

**Review by JLyons1985 — APPROVED** [review]

**Pull request merged**
